/*---------------------------------------------------------------------------------------------
 *  Copyright (c) PCL-N Edition contributors. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';
import { buildNplugFromParts, writeNplug } from './nplug';

export interface CreateProjectOptions {
	readonly parentDir: string;
	readonly pluginId: string;
	readonly pluginName: string;
	readonly author: string;
	readonly sdkVersion: string;
}

function writeFile(filePath: string, content: string): void {
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, content, 'utf8');
}

export function toAssemblyName(pluginId: string): string {
	const last = pluginId.split(/[.-]/).filter(Boolean).pop() ?? 'Plugin';
	let name = last
		.split(/[-_]/)
		.filter(Boolean)
		.map(part => part.charAt(0).toUpperCase() + part.slice(1))
		.join('');
	if (!/^[A-Za-z_]/.test(name)) {
		name = `PclPlugin${name}`;
	}
	return name || 'PclPlugin';
}

export async function createHelloPclProject(options: CreateProjectOptions): Promise<string> {
	const { parentDir, pluginId, pluginName, author, sdkVersion } = options;
	const assembly = toAssemblyName(pluginId);
	const projectDir = path.join(parentDir, assembly);
	if (fs.existsSync(projectDir) && fs.readdirSync(projectDir).length > 0) {
		throw new Error(`Target directory is not empty: ${projectDir}`);
	}

	const projectFileName = `${assembly}.csproj`;
	const solutionFileName = `${assembly}.slnx`;
	const nplugFileName = `${assembly}.nplug`;
	const namespace = pluginId.includes('.') ? pluginId.slice(0, pluginId.lastIndexOf('.')) : pluginId;
	const nplug = buildNplugFromParts({
		id: pluginId,
		name: pluginName,
		sdkVersion,
		author,
		description: `${pluginName} — generated by PCL NE Plugin IDE Community Edition`,
		assemblyName: assembly,
		projectFileName,
		solutionFileName,
	});

	writeNplug(path.join(projectDir, nplugFileName), nplug);
	writeFile(path.join(projectDir, solutionFileName), `<Solution>
  <Project Path="${projectFileName}" />
</Solution>
`);
	writeFile(path.join(projectDir, projectFileName), `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.1.0</Version>
    <AssemblyName>${assembly}</AssemblyName>
    <RootNamespace>${assembly}</RootNamespace>
    <PclNPluginId>${pluginId}</PclNPluginId>
    <PclNPluginSign>false</PclNPluginSign>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PCLN.Plugin.Abstractions" Version="${sdkVersion}" />
    <PackageReference Include="PCLN.Plugin.Sdk" Version="${sdkVersion}" PrivateAssets="all" />
    <PackageReference Include="PCLN.Plugin.Analyzers" Version="${sdkVersion}" PrivateAssets="all" />
    <PackageReference Include="PCLN.Plugin.Sdk.Build" Version="${sdkVersion}" PrivateAssets="all" />
    <AdditionalFiles Include="plugin.json" />
  </ItemGroup>
</Project>
`);
	writeFile(path.join(projectDir, 'plugin.json'), JSON.stringify({
		formatVersion: 1,
		manifestVersion: 1,
		id: pluginId,
		name: pluginName,
		version: '0.1.0',
		channel: 'alpha',
		summary: `${pluginName} plugin.`,
		publisher: {
			id: `local:${author.toLowerCase().replace(/[^a-z0-9]+/g, '-') || 'developer'}`,
			namespace,
		},
		authors: [{ name: author }],
		license: 'MIT',
		entryPoint: {
			assembly: `lib/net10.0/${assembly}.dll`,
			type: `${assembly}.HelloPlugin`,
		},
		api: { minimum: '0.1', maximumExclusive: '1.0' },
		host: { minimumVersion: '0.2.5' },
		localization: {
			defaultCulture: 'zh-CN',
			supportedCultures: ['zh-CN', 'en-US'],
			resourcePath: 'locales/{culture}.json',
		},
		signing: { fingerprint: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' },
		categories: ['tools'],
		tags: ['community'],
	}, null, '\t') + '\n');
	writeFile(path.join(projectDir, 'src', 'HelloPlugin.cs'), `using PCL.N.Plugin;

namespace ${assembly};

public sealed class HelloPlugin : IPclNPlugin
{
	public ValueTask InitializeAsync(IPluginContext context, CancellationToken cancellationToken)
	{
		cancellationToken.ThrowIfCancellationRequested();
		context.Logger.Info($"{context.Plugin.Name} loaded with API {context.ApiVersion}.");
		if (context.Services.TryGet<IPluginNotificationService>(out var notifications))
		{
			notifications.ShowInformation("Hello from ${pluginName}!");
		}
		return ValueTask.CompletedTask;
	}

	public ValueTask ShutdownAsync(CancellationToken cancellationToken) => ValueTask.CompletedTask;
}
`);
	writeFile(path.join(projectDir, 'locales', 'zh-CN.json'), JSON.stringify({ 'plugin.name': pluginName }, null, '\t') + '\n');
	writeFile(path.join(projectDir, 'locales', 'en-US.json'), JSON.stringify({ 'plugin.name': pluginName }, null, '\t') + '\n');
	writeFile(path.join(projectDir, 'README.md'), `# ${pluginName}

Generated by **PCL NE Plugin IDE Community Edition** with Public PNPSDK ${sdkVersion}.

Use the PCL commands to restore, build, create a development-signed .pnp package, and validate it.
`);
	return projectDir;
}

export async function promptCreateProject(sdkVersion: string): Promise<CreateProjectOptions | undefined> {
	const parentUri = await vscode.window.showOpenDialog({
		canSelectFiles: false,
		canSelectFolders: true,
		canSelectMany: false,
		openLabel: vscode.l10n.t('Select Parent Folder'),
		title: vscode.l10n.t('New Plugin Project — Select Parent Folder'),
	});
	if (!parentUri?.length) {
		return undefined;
	}
	const pluginId = await vscode.window.showInputBox({
		title: vscode.l10n.t('New Plugin Project'),
		prompt: vscode.l10n.t('Plugin Id (lower-case reverse-domain format)'),
		value: 'dev.example.hello',
		validateInput: value => /^[a-z0-9]+([.-][a-z0-9]+)*$/.test(value)
			? undefined
			: vscode.l10n.t('Use a lower-case identifier such as dev.example.hello'),
	});
	if (!pluginId) {
		return undefined;
	}
	const pluginName = await vscode.window.showInputBox({
		title: vscode.l10n.t('New Plugin Project'),
		prompt: vscode.l10n.t('Display name'),
		value: 'Hello PCL',
		validateInput: value => value?.trim() ? undefined : vscode.l10n.t('Name is required'),
	});
	if (!pluginName) {
		return undefined;
	}
	const author = await vscode.window.showInputBox({
		title: vscode.l10n.t('New Plugin Project'),
		prompt: vscode.l10n.t('Author'),
		value: 'Community Developer',
	}) ?? 'Community Developer';
	return { parentDir: parentUri[0].fsPath, pluginId, pluginName, author, sdkVersion };
}
