/*---------------------------------------------------------------------------------------------
 *  Copyright (c) PCL-N Edition contributors. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';

export interface CreateProjectOptions {
	readonly targetDir: string;
	readonly pluginId: string;
	readonly pluginName: string;
	readonly author: string;
	readonly sdkVersion: string;
}

function writeFile(filePath: string, content: string): void {
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	fs.writeFileSync(filePath, content, 'utf8');
}

function toAssemblyName(pluginId: string): string {
	const last = pluginId.split('.').pop() ?? 'Plugin';
	return last
		.split(/[-_]/)
		.filter(Boolean)
		.map(part => part.charAt(0).toUpperCase() + part.slice(1))
		.join('');
}

export async function createHelloPclProject(options: CreateProjectOptions): Promise<string> {
	const { targetDir, pluginId, pluginName, author, sdkVersion } = options;
	const assembly = toAssemblyName(pluginId);
	const projectDir = path.join(targetDir, assembly);

	if (fs.existsSync(projectDir) && fs.readdirSync(projectDir).length > 0) {
		throw new Error(`Target directory is not empty: ${projectDir}`);
	}

	fs.mkdirSync(projectDir, { recursive: true });
	fs.mkdirSync(path.join(projectDir, 'src'), { recursive: true });

	writeFile(path.join(projectDir, 'plugin.manifest.json'), JSON.stringify({
		schemaVersion: '1.0',
		id: pluginId,
		name: pluginName,
		version: '0.1.0',
		sdkVersion,
		description: `${pluginName} — generated by PCL NE Plugin IDE Community Edition`,
		author,
		license: 'MIT',
		entry: {
			assembly: `bin/${assembly}.dll`,
			type: `${assembly}.PluginEntry`,
		},
		permissions: ['ui'],
		localization: {
			defaultCulture: 'en',
			cultures: ['en'],
		},
	}, null, '\t') + '\n');

	writeFile(path.join(projectDir, `${assembly}.csproj`), `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>${assembly}</AssemblyName>
    <RootNamespace>${assembly}</RootNamespace>
    <OutputPath>bin\\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
</Project>
`);

	writeFile(path.join(projectDir, 'src', 'PluginEntry.cs'), `namespace ${assembly};

/// <summary>
/// Minimal PCL-N plugin entry point used by the Community Edition template.
/// Replace with Public PNPSDK base types when the SDK package is available.
/// </summary>
public sealed class PluginEntry
{
	public string Id => "${pluginId}";
	public string Name => "${pluginName}";

	public void OnLoad()
	{
		// Plugin initialization hook.
	}
}
`);

	writeFile(path.join(projectDir, 'README.md'), `# ${pluginName}

Generated by **PCL NE Plugin IDE Community Edition**.

## Workflow

1. \`PCL: Check Environment\`
2. \`PCL: Build Plugin\`
3. \`PCL: Development Sign Package\`
4. \`PCL: Package Plugin (.pnp)\`
5. \`PCL: Validate Plugin Package\`

Plugin id: \`${pluginId}\`
`);

	return projectDir;
}

export async function promptCreateProject(sdkVersion: string): Promise<CreateProjectOptions | undefined> {
	const folders = vscode.workspace.workspaceFolders;
	if (!folders?.length) {
		void vscode.window.showErrorMessage('Open a folder before creating a PCL plugin project.');
		return undefined;
	}

	const pluginId = await vscode.window.showInputBox({
		title: 'PCL Plugin Id',
		prompt: 'Reverse-DNS identifier',
		value: 'com.example.hello-pcl',
		validateInput: value => {
			if (!value || !/^[a-z0-9]+(\.[a-z0-9\-]+)+$/.test(value)) {
				return 'Use reverse-DNS form, e.g. com.example.hello-pcl';
			}
			return undefined;
		},
	});
	if (!pluginId) {
		return undefined;
	}

	const pluginName = await vscode.window.showInputBox({
		title: 'PCL Plugin Name',
		value: 'Hello PCL',
		validateInput: value => value?.trim() ? undefined : 'Name is required',
	});
	if (!pluginName) {
		return undefined;
	}

	const author = await vscode.window.showInputBox({
		title: 'Author',
		value: 'Community Developer',
	}) ?? 'Community Developer';

	return {
		targetDir: folders[0].uri.fsPath,
		pluginId,
		pluginName,
		author,
		sdkVersion,
	};
}
